version: "3.9"

services:
  backend:
    build: .
    container_name: manhattan-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: shoptech/Dockerfile
    container_name: manhattan-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
