name: Frontend CI/CD

on:
  push:
    branches: [ "main", "develop", "feature/order" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies and set API URL
      - name: Set API URL and install dependencies
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > shoptech/.env
          cd shoptech
          npm install

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/manhattan-frontend:${{ github.ref_name }}
          echo "Building Docker image $IMAGE_NAME..."
          docker build -t $IMAGE_NAME .
          echo "Pushing Docker image $IMAGE_NAME..."
          docker push $IMAGE_NAME

      # Step 6: Run Trivy vulnerability scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/manhattan-frontend:${{ github.ref_name }}
          format: 'table'
          ignore-unfixed: true
          exit-code: '0'   # Do not fail pipeline
          vuln-type: 'os,library'

      # Step 7: Deploy to AWS via SSH
      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/manhattan-frontend:${{ github.ref_name }}
            echo "Pulling Docker image $IMAGE_NAME..."
            docker pull $IMAGE_NAME
            echo "Stopping old container (if exists)..."
            docker stop frontend || true
            docker rm frontend || true
            echo "Running new container..."
            docker run -d --name frontend -p 80:80 $IMAGE_NAME
